version: '3.9'

services:
  backend:
    container_name: web
    build:
        context: .
        dockerfile: Dockerfile
    environment:
        - ETH_PRIVATE_KEY=""
        - SOL_PRIVATE_KEY=""
    restart: always
    ports:
        - 8001:8001

  # docker run --platform=linux/amd64 -p 7073:7073 --entrypoint /guardiand ghcr.io/wormhole-foundation/guardiand:latest spy --nodeKey /node.key --spyRPC \"[::]:7073\" --network /wormhole/mainnet/2 --bootstrap /dns4/wormhole-mainnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWQp644DK27fd3d4Km3jr7gHiuJJ5ZGmy8hH4py7fP4FP7

  mainnet-spy:
    container_name: mainnet-spy
    image: ghcr.io/wormhole-foundation/guardiand:latest
    entrypoint: /guardiand
    command: 
      - spy
      - --nodeKey
      - /node.key
      - --spyRPC
      - "[::]:7073"
      - --network
      - /wormhole/mainnet/2
      - --bootstrap
      - /dns4/wormhole-mainnet-v2-bootstrap.certus.one/udp/8999/quic/p2p/12D3KooWQp644DK27fd3d4Km3jr7gHiuJJ5ZGmy8hH4py7fP4FP7
    ports:
      - 7073:7073

  # webserver:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./nginx
  #   ports:
  #     - "80:80"
  #     - 443:443
  #   depends_on:
  #     - backend